on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  linux:
    name: Build Linux wheels
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build wheels
        uses: messense/maturin-action@v1.30.2
        with:
          manylinux: auto
          args: --release --out dist -m pyaerso/Cargo.toml

      - name: Upload wheels
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: pyaerso/dist
  
  windows:
    name: Build Windows wheels
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build wheels
        uses: messense/maturin-action@v1.30.2
        with:
          args: --release --out dist -m pyaerso/Cargo.toml
      
      - name: Upload wheels
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: pyaerso/dist
